# Generated by Django 2.1.7 on 2019-02-26 05:20

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_frame_name', models.CharField(max_length=150)),
                ('data_frame', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
