# Generated by Django 2.1.7 on 2019-02-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframemodel',
            name='data_frame_name',
            field=models.CharField(help_text='data frame description', max_length=150),
        ),
    ]
