# Generated by Django 2.1.7 on 2019-02-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190227_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframemodel',
            name='data_frame_name',
            field=models.CharField(max_length=150),
        ),
    ]
