# Generated by Django 2.1.7 on 2019-02-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190227_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframemodel',
            name='data_frame',
            field=models.CharField(max_length=100),
        ),
    ]
