# Generated by Django 2.1.7 on 2019-02-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190227_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataframemodel',
            name='data_frame',
        ),
        migrations.AddField(
            model_name='dataframemodel',
            name='data_frame_path',
            field=models.CharField(blank='null', max_length=150),
        ),
    ]
