# Generated by Django 2.1.7 on 2019-03-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190227_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataframemodel',
            old_name='data_frame_name',
            new_name='df_description',
        ),
        migrations.RenameField(
            model_name='dataframemodel',
            old_name='data_frame_path',
            new_name='df_stroed_name',
        ),
    ]
